
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Mar 08 22:52:21 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 35;
  public static final int CHAR = 53;
  public static final int CONST = 7;
  public static final int SLASH_ASSIGN = 40;
  public static final int ASTERISK = 23;
  public static final int SLASH = 24;
  public static final int PLUS_ASSIGN = 37;
  public static final int GRT = 28;
  public static final int LPAREN = 42;
  public static final int PRIVATE = 20;
  public static final int CONTINUE = 16;
  public static final int INT = 52;
  public static final int ASTERISK_ASSIGN = 39;
  public static final int LSS = 30;
  public static final int FOR = 14;
  public static final int MINUS = 22;
  public static final int RPAREN = 43;
  public static final int SEMICOLON = 49;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int BOOL = 54;
  public static final int COMMA = 50;
  public static final int CLASS = 4;
  public static final int GEQ = 29;
  public static final int PLUS = 21;
  public static final int ASSIGN = 34;
  public static final int IF = 8;
  public static final int DOT = 51;
  public static final int ABSTRACT = 5;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 36;
  public static final int RETURN = 12;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PERCENT = 25;
  public static final int NEQ = 27;
  public static final int IDENT = 55;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int LBRACK = 44;
  public static final int COLON = 48;
  public static final int FOREACH = 17;
  public static final int LBRACE = 46;
  public static final int ELSE = 6;
  public static final int PROTECTED = 19;
  public static final int RBRACK = 45;
  public static final int READ = 11;
  public static final int EQL = 26;
  public static final int PUBLIC = 18;
  public static final int RBRACE = 47;
  public static final int EXTENDS = 15;
  public static final int LEQ = 31;
  public static final int PERCENT_ASSIGN = 41;
  public static final int MINUS_ASSIGN = 38;
  public static final int PRINT = 10;
}

